
print("Hello, World! dev xavier")
print("acordei")
print("Levantei")
print("abri a porta do quarto")
print("caminhei ate banheiro")
print("abri a porta do banheiro")
print("entrei no banheiro")
print("peguei a pasta e a escova")
print("escovei os dentes")
print("abri a torneira")
print("enxaguei os dentes")
print("fechei a torneira")
print("fui ate o chuveiro")
print("abri o registro do chuveiro")
print("me ensaboei")
print("me enxaguei")
print("peguei a toalha para me secar")
